### ISSUE TITLE
X11 in RStudio

### ISSUE THREAD

**Issue by Lauren-Blake** [jdblischak/giladlab-midway-guide#1]
Hi John,

I am using RStudio on Midway (specifically, the R package "maSigPro") and while the vast majority of commands run fine, there is a specific command that uses X11. When I try to run the command or create an Markdown file with the command included, I get the following error message 

**Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  : 
  unable to start device X11cairo
In addition: Warning message:
In X11() : unable to open connection to X11 display ''**

When I looked at the available modules on Midway, there did not appear to be anything about X11. I also didn't see anything about it on your User's Guide or the Midway User's Guide (they talked about "X11 forwarding" but that did not seem to be the same topic). Any suggestions before I email the RCC help people?

Thanks

**Comment by jdblischak** [comment]
Could you please provide a small code chunk that I can run to reproduce the error message?

**Comment by jdblischak** [comment]
Closing. Please post here if you found a solution. Also feel free to re-open if you have the same issue again.
