### ISSUE TITLE
override default R version

### ISSUE THREAD

**Issue by jhsiao999** [jdblischak/giladlab-midway-guide#2]
I want to use a version that's same as my desktop computer and put in the following my `.bashrc`.

`module load R/3.3`

When I did `Rscript --version`, I got 

`R scripting front-end version 3.4.0 (2017-04-21)`

Is there a way to override the default R version on midway? 

Thanks!!

**Comment by jdblischak** [comment]
After editing your `.bashrc`, you need to re-execute the file for the setting to take effect. You can run `source ~/.bashrc` or logout and log back in. Please let me know if that doesn't work.

Also, for future questions, please specify if you are using Midway1, Midway2, or the mstephens partition. The options for configuring R are different for each of these 3 options.

**Comment by jhsiao999** [comment]
Great. Thanks so much! It worked by simply logging out and logging in...

By the way, I was using Midway2.
